language: ruby
rvm:
  - 2.2.2
sudo: false
before_script:
  - npm install bower -g
  - bower install
script:
  - export RAILS_ENV=test
  - bundle exec rake --trace db:migrate test
notifications:
  email: false
